# -*- coding: utf-8 -*-
"""p1_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-vyinCnp811-OetFxxiosvDrXJntOh0Y
"""

#士兵
checkerboard =[

[1, 0, 0, 0, 0, 0, 0, 0],

[0, 0, 0, 0, 0, 0, 0, 0],

[0, 0, 0, 0, 0, 0, 0, 0],

[0, 0, 0, 0, 0, 0, 0, 0],

[0, 0, 0, 0, 0, 0, 0, 0],

[0, 0, 0, 0, 0, 0, 0, 0],

[0, 0, 0, 0, 0, 0, 0, 0],

[0, 0, 0, 0, 0, 0, 0, 0]

]

position1 = list(map(int,input().split()))
position2 = list(map(int,input().split()))
x1,y1 = position1[0], position1[1]
x2,y2 = position2[0], position2[1]

if (x2 == x1 + 1) and (y2 == y1) and (checkerboard[x2][y2] == 0):
  print("Yes")
else:
  print("No")