# -*- coding: utf-8 -*-
"""p1_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vfUCrhDS_3LnTjSR7rhzdrTiWenGX9yN
"""

#國王
checkerboard = [
    [1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0]
]

position1 = list(map(int, input().split()))
position2 = list(map(int, input().split()))
x1, y1 = position1[0], position1[1]
x2, y2 = position2[0], position2[1]

dx = abs(x2 - x1)
dy = abs(y2 - y1)

if (dx <= 1 and dy <= 1) and checkerboard[x2][y2] == 0 and (x1 != x2 or y1 != y2):
    print("Yes")
else:
    print("No")