# -*- coding: utf-8 -*-
"""p1_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o1pzfPUk3VlHHs0MISCgxQriE-ucnogG
"""

#皇后
checkerboard = [
    [1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0]
]

position1 = list(map(int, input().split()))
position2 = list(map(int, input().split()))
x1, y1 = position1[0], position1[1]
x2, y2 = position2[0], position2[1]

n = 8
can_move = False

if x1 == x2 and y1 == y2:
    can_move = False
else:
    # 檢查水平移動
    if y1 == y2:
        blocked = False
        for x in range(min(x1, x2) + 1, max(x1, x2)):
            if 0 <= x < n and checkerboard[x][y1] == 1:
                blocked = True
                break
        if not blocked:
            can_move = True
    # 檢查垂直移動
    elif x1 == x2:
        blocked = False
        for y in range(min(y1, y2) + 1, max(y1, y2)):
            if 0 <= y < n and checkerboard[x1][y] == 1:
                blocked = True
                break
        if not blocked:
            can_move = True
    # 檢查斜線移動
    elif abs(x1 - x2) == abs(y1 - y2):
        step_x = 1 if x2 > x1 else -1
        step_y = 1 if y2 > y1 else -1
        x, y = x1 + step_x, y1 + step_y
        blocked = False
        while x != x2:
            if 0 <= x < n and 0 <= y < n and checkerboard[x][y] == 1:
                blocked = True
                break
            x += step_x
            y += step_y
        if not blocked:
            can_move = True

if can_move:
    print("Yes")
else:
    print("No")